---
title: "liu_meta"
output: html_document
---

```{r setup}
library(dplyr)
library(ggplot2)
library(cmdstanr)
library(bayesplot)

REPO_DIR <- "~/Imperial/0_Research/modular_bayes/"
```

```{r experiment-config}
config <- list(
    n1 = 25,
    n2 = 50,
    mu = 0,
    theta = 1,
    s1 = 2,
    s2 = 1
)
```

```{r}
# Function to generate data for the simulation study
generate_data <- function(n1, n2, mu, theta, s1, s2) {
    z <- rnorm(n1, mean = mu, sd = s1)
    y <- rnorm(n2, mean = mu + theta, sd = s2)

    return(list(y = y, z = z))
}

set.seed(5)
data <- generate_data(
    n1 = config$n1,
    n2 = config$n2,
    mu = config$mu,
    theta = config$theta,
    s1 = config$s1,
    s2 = config$s2
)
```

```{r sanity-check}
ggplot() +
  geom_histogram(aes(x = data$z), bins = 10, fill = "blue", alpha = 0.7) +
  geom_histogram(aes(x = data$y), bins = 10, fill = "red", alpha = 0.7) + 
  labs(title = "Histograms of Simulated Data", x = "Value", y = "Frequency") +
  theme_bw() +
  theme(aspect.ratio = 1)
```
Fit the first stage model
```{r prepare-data-for-stan}
stan_data <- list(
    n1 = config$n1,
    z = data$z
)
```

```{r fit-model}
model_m1 <- cmdstan_model("../../stan/liu_m1.stan")
fit_m1 <- model_m1$sample(
    data = stan_data,
    chains = 4,
    parallel_chains = 4,
    iter_warmup = 1000,
    iter_sampling = 1000,
    seed = 1234,
    show_messages=FALSE
)
```

```{r}
# Full posterior
post_m1 <- fit_m1$draws(format = "draws_matrix")
sum_m1 <- fit_m1$summary("mu")
sum_m1

# Extract posterior draws
post_draws_mu <- as.numeric(post_m1[,"mu"])
```

Fit the second stage data
```{r}
stan_data <- list(
  M = length(post_draws_mu),
  mu = post_draws_mu,
  n2 = config$n2,
  y = data$y
)

model_cut <- cmdstan_model("../../stan/liu_m2_cut.stan")
fit_meta <- model_cut$sample(
    data = stan_data,
    chains = 4,
    parallel_chains = 4,
    iter_warmup = 1000,
    iter_sampling = 1000,
    seed = 1234,
    show_messages=FALSE
)
```

```{r posterior-summary}
post_cut <- fit_meta$draws(format = "draws_matrix")
sum_cut <- fit_meta$summary(c("theta"))

sum_cut
```

```{r}
mcmc_areas(post_cut, pars = c("theta")) + 
  theme_bw() +
  theme(aspect.ratio = 1)
```

```{r}
stan_data <- list(
  z = data$z,
  y = data$y,
  n1 = config$n1,
  n2 = config$n2
)

model_full <- cmdstan_model("../../stan/liu_full.stan")
fit_full <- model_full$sample(
    data = stan_data,
    chains = 4,
    parallel_chains = 4,
    iter_warmup = 1000,
    iter_sampling = 1000,
    seed = 1234,
    show_messages=FALSE
)
```

```{r}
post_full <- fit_full$draws(c("theta", "mu"), format = "draws_matrix")
sum_full <- fit_full$summary(c("theta", "mu"))
sum_full

mcmc_areas(post_full, pars = c("theta", "mu")) + theme_bw() + theme(aspect.ratio = 1)
```
